---
title: "7 Sensitivity analysis - Scenario Comparison"
author: "Simon Chiu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
gc()

library(progress)
library(tidyverse)
library(openxlsx)
library(ggplot2)
library(patchwork)
library(ggh4x)
library(ggpubr)
library(ggbrace)

# devtools::install_github("nicolash2/ggbrace")

focus_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/focus_df_2023-07-18.RDS")
sensitivity_ran_variables<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/sensitivity_ran_variables_2023-07-17.RDS")
det_bmi_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/det_bmi_df_2023-07-16.RDS") %>%
  rename("bmi.output"="bmi", "age.groups.output"="age.groups", "gender.output"="gender")
det_bmi_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/det_bmi_df_2023-07-16.RDS") %>%
  rename("bmi.output"="bmi", "age.groups.output"="age.groups", "gender.output"="gender")
load("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_seq_sample_2023-07-16.RData")
lsa_bmi_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_bmi_df_2023-07-18.RDS")

lsa.sensivity.seq.sample<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_sensivity_seq_sample_2023-07-17.RDS")


focus_df_epoch<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/focus_df_epoch_2023-07-16.RDS")
focus_df_cci<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/focus_df_cci_2023-07-16.RDS")
focus_df_si<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/focus_df_si_2023-07-16.RDS")
focus_df_svi<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/focus_df_svi_2023-07-16.RDS")
focus_df_ssb<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/focus_df_ssb_2023-07-16.RDS")

lsa_int_epoch_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_int_epoch_df_2023-07-30.RDS")
lsa_int_cci_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_int_cci_df_2023-07-30.RDS")
lsa_int_si_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_int_si_df_2023-07-30.RDS")
lsa_int_svi_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_int_svi_df_2023-08-01.RDS")
lsa_int_ssb_df<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/lsa_int_ssb_df_2023-07-30.RDS")

derivative_lsa_epoch_int<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/derivative_lsa_epoch_int_2023-07-31.RDS")
derivative_lsa_cci_int<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/derivative_lsa_cci_int_2023-07-31.RDS")
derivative_lsa_si_int<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/derivative_lsa_si_int_2023-07-31.RDS")
derivative_lsa_svi_int<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/derivative_lsa_svi_int_2023-08-01.RDS")
derivative_lsa_ssb_int<-readRDS("/media/simon/ExtSSD/Documents/PhD/4 SD Model/7 Sensitivity/Data/R/derivative_lsa_ssb_int_2023-07-31.RDS")

det_bmi_df_wide<-det_bmi_df %>% 
  filter(scenario!="Base model") %>% 
  rename('det.int.value'='2057') %>% 
  select("scenario" ,"run","bmi.output","age.groups.output","gender.output", "det.int.value") %>% 
  left_join(., det_bmi_df %>% 
              filter(scenario=="Base model") %>% 
              rename('det.base.model.value'='2057') %>% 
              select("bmi.output","age.groups.output","gender.output", "det.base.model.value"),
            by=c("bmi.output","age.groups.output","gender.output"))

lsa_int_epoch_df<-lsa_int_epoch_df %>% 
  mutate(scenario=factor(case_when(scenario == "1 EPOCH"~1,
                                 scenario == "2 CCI"~2,
                                 scenario == "3 SI"~3,
                                 scenario == "4 SVI"~4,
                                 scenario == "5 SSB"~5,
                                 scenario == "6 EPOCH CCI"~6,
                                 scenario == "7 SI SVI"~7,
                                 scenario == "8 EPOCH CCI SI SVI"~8,
                                 scenario == "9 EPOCH CCI SI SVI SSB"~9),
                       levels=c(1:9),
                       labels = c("EPOCH", "CCI", "SI", "SVI", "SSB", "EPOCH+CCI",
                                  "SI+SVI",  "EPOCH+CCI+SI+SVI", "EPOCH+CCI+SI+SVI+SSB"))) %>% 
left_join(., det_bmi_df_wide %>% select(-run),
          by=c("scenario","bmi.output","age.groups.output","gender.output"))

lsa_int_cci_df<-lsa_int_cci_df %>% 
  mutate(scenario=factor(case_when(scenario == "1 EPOCH"~1,
                                 scenario == "2 CCI"~2,
                                 scenario == "3 SI"~3,
                                 scenario == "4 SVI"~4,
                                 scenario == "5 SSB"~5,
                                 scenario == "6 EPOCH CCI"~6,
                                 scenario == "7 SI SVI"~7,
                                 scenario == "8 EPOCH CCI SI SVI"~8,
                                 scenario == "9 EPOCH CCI SI SVI SSB"~9),
                       levels=c(1:9),
                       labels = c("EPOCH", "CCI", "SI", "SVI", "SSB", "EPOCH+CCI",
                                  "SI+SVI",  "EPOCH+CCI+SI+SVI", "EPOCH+CCI+SI+SVI+SSB"))) %>% 
left_join(., det_bmi_df_wide %>% select(-run),
          by=c("scenario","bmi.output","age.groups.output","gender.output"))

lsa_int_si_df<-lsa_int_si_df %>% 
  mutate(scenario=factor(case_when(scenario == "1 EPOCH"~1,
                                 scenario == "2 CCI"~2,
                                 scenario == "3 SI"~3,
                                 scenario == "4 SVI"~4,
                                 scenario == "5 SSB"~5,
                                 scenario == "6 EPOCH CCI"~6,
                                 scenario == "7 SI SVI"~7,
                                 scenario == "8 EPOCH CCI SI SVI"~8,
                                 scenario == "9 EPOCH CCI SI SVI SSB"~9),
                       levels=c(1:9),
                       labels = c("EPOCH", "CCI", "SI", "SVI", "SSB", "EPOCH+CCI",
                                  "SI+SVI",  "EPOCH+CCI+SI+SVI", "EPOCH+CCI+SI+SVI+SSB"))) %>% 
left_join(., det_bmi_df_wide %>% select(-run),
          by=c("scenario","bmi.output","age.groups.output","gender.output"))

lsa_int_svi_df<-lsa_int_svi_df %>% 
  mutate(scenario=factor(case_when(scenario == "1 EPOCH"~1,
                                 scenario == "2 CCI"~2,
                                 scenario == "3 SI"~3,
                                 scenario == "4 SVI"~4,
                                 scenario == "5 SSB"~5,
                                 scenario == "6 EPOCH CCI"~6,
                                 scenario == "7 SI SVI"~7,
                                 scenario == "8 EPOCH CCI SI SVI"~8,
                                 scenario == "9 EPOCH CCI SI SVI SSB"~9),
                       levels=c(1:9),
                       labels = c("EPOCH", "CCI", "SI", "SVI", "SSB", "EPOCH+CCI",
                                  "SI+SVI",  "EPOCH+CCI+SI+SVI", "EPOCH+CCI+SI+SVI+SSB"))) %>% 
left_join(., det_bmi_df_wide %>% select(-run),
          by=c("scenario","bmi.output","age.groups.output","gender.output"))

lsa_int_ssb_df<-lsa_int_ssb_df %>% 
  mutate(scenario=factor(case_when(scenario == "1 EPOCH"~1,
                                 scenario == "2 CCI"~2,
                                 scenario == "3 SI"~3,
                                 scenario == "4 SVI"~4,
                                 scenario == "5 SSB"~5,
                                 scenario == "6 EPOCH CCI"~6,
                                 scenario == "7 SI SVI"~7,
                                 scenario == "8 EPOCH CCI SI SVI"~8,
                                 scenario == "9 EPOCH CCI SI SVI SSB"~9),
                       levels=c(1:9),
                       labels = c("EPOCH", "CCI", "SI", "SVI", "SSB", "EPOCH+CCI",
                                  "SI+SVI",  "EPOCH+CCI+SI+SVI", "EPOCH+CCI+SI+SVI+SSB"))) %>% 
left_join(., det_bmi_df_wide %>% select(-run),
          by=c("scenario","bmi.output","age.groups.output","gender.output"))

```

# EPOCH

## RCT Effects
```{r RCT Effects, echo=F, message=F, error=F, warning=F, fig.height=1*3*2.7, fig.width=1*2*2.7}
derivative_lsa_epoch_int %>% 
  filter(focus=="Effect BF OR") %>% 
  # filter(gender.output=='Male') %>%
  ggplot()+
  geom_point(aes(x=age.groups.output, y=mean.ee.alt/100, color=bmi.output), size=1)+
  geom_line(aes(x=as.numeric(age.groups.output), y=mean.ee.alt/100, color=bmi.output))+
  # geom_smooth(aes(x=as.numeric(age.groups.output), y=mean.ee.alt, color=bmi.output), se=F, linewidth=0.5)+
  facet_grid(col=vars(gender.output), scale="free")+
  scale_x_discrete(breaks=c("Age 3 5", "Age 18 19", "Age 40 44"),
                   labels=c("3 5", "18 19", "40 44"))+
  xlab("Age group")+ylab(expression(mu[EE]))+
  theme_bw()+
  scale_y_continuous(labels = scales::label_number(suffix = "%", scale =1))+
  guides(colour = guide_legend("BMI"))+
  ggtitle("Effect BF OR", subtitle = "Per 0.01 units")+
  
  derivative_lsa_epoch_int %>% 
  filter(focus=="Effect TV OR") %>% 
  # filter(gender.output=='Male') %>%
  ggplot()+
  geom_point(aes(x=age.groups.output, y=mean.ee.alt/100, color=bmi.output), size=1)+
  geom_line(aes(x=as.numeric(age.groups.output), y=mean.ee.alt/100, color=bmi.output))+
  # geom_smooth(aes(x=as.numeric(age.groups.output), y=mean.ee.alt, color=bmi.output), se=F, linewidth=0.5)+
  facet_grid(col=vars(gender.output), scale="free")+
  scale_x_discrete(breaks=c("Age 3 5", "Age 18 19", "Age 40 44"),
                   labels=c("3 5", "18 19", "40 44"))+
  xlab("Age group")+ylab(expression(mu[EE]))+
  theme_bw()+
  scale_y_continuous(labels = scales::label_number(suffix = "%", scale =1))+
  guides(colour = guide_legend("BMI"))+
  ggtitle("Effect TV OR", subtitle = "Per 0.01 units")+
  
  derivative_lsa_epoch_int %>% 
  filter(focus=="\"Effect Non-core OR\"") %>% 
  # filter(gender.output=='Male') %>%
  ggplot()+
  geom_point(aes(x=age.groups.output, y=mean.ee.alt/100, color=bmi.output), size=1)+
  geom_line(aes(x=as.numeric(age.groups.output), y=mean.ee.alt/100, color=bmi.output))+
  # geom_smooth(aes(x=as.numeric(age.groups.output), y=mean.ee.alt, color=bmi.output), se=F, linewidth=0.5)+
  facet_grid(col=vars(gender.output), scale="free")+
  scale_x_discrete(breaks=c("Age 3 5", "Age 18 19", "Age 40 44"),
                   labels=c("3 5", "18 19", "40 44"))+
  xlab("Age group")+ylab(expression(mu[EE]))+
  theme_bw()+
  scale_y_continuous(labels = scales::label_number(suffix = "%", scale =1))+
  guides(colour = guide_legend("BMI"))+
  ggtitle("Effect Non-core OR", subtitle = "Per 0.01 units")+
  
  plot_layout(ncol = 1, nrow=3, guides = "collect")&theme(legend.position = "bottom")
  
  
  
  

```



